services:
  - type: web
    name: script-host
    env: python
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
